name: mlflow-env

channels:
  - conda-forge

dependencies:
  - python=3.12.6
  - pip
  - pip:
      - mlflow==3.8.0
      - numpy==1.26.4
      - pandas==2.2.2
      - scikit-learn==1.6.1
      - matplotlib==3.9.2